#include "main.h"

//WIFI-DMX.COM


void PWM_SetOutputChannel(PWM_T *pwm,uint32_t u32ChannelNum, uint16_t Timerperiod,uint16_t PWMduty, uint8_t u8Switch,uint32_t Prescaler)
{
    // every two channels share a prescaler
    PWM_SET_PRESCALER(pwm, u32ChannelNum, Prescaler); // Divided by 1
    // set PWM to down count type(edge aligned)
    (pwm)->CTL1 = ((pwm)->CTL1 & ~(PWM_CTL1_CNTTYPE0_Msk << (2 * u32ChannelNum))) | (1UL << (2 * u32ChannelNum));

    PWM_SET_CNR(pwm, u32ChannelNum, Timerperiod);
    if(u8Switch)
    {
        PWM_SET_CMR(pwm, u32ChannelNum, PWMduty);
        (pwm)->WGCTL0 &= ~((PWM_WGCTL0_PRDPCTL0_Msk | PWM_WGCTL0_ZPCTL0_Msk) << (u32ChannelNum * 2));
        (pwm)->WGCTL0 |= (PWM_OUTPUT_LOW << (u32ChannelNum * 2 + PWM_WGCTL0_PRDPCTL0_Pos));
        (pwm)->WGCTL1 &= ~((PWM_WGCTL1_CMPDCTL0_Msk | PWM_WGCTL1_CMPUCTL0_Msk) << (u32ChannelNum * 2));
        (pwm)->WGCTL1 |= (PWM_OUTPUT_HIGH << (u32ChannelNum * 2 + PWM_WGCTL1_CMPDCTL0_Pos));
    }
    else
    {
        PWM_SET_CMR(pwm, u32ChannelNum, PWMduty);
        (pwm)->WGCTL0 &= ~((PWM_WGCTL0_PRDPCTL0_Msk | PWM_WGCTL0_ZPCTL0_Msk) << (u32ChannelNum * 2));
        (pwm)->WGCTL0 |= (PWM_OUTPUT_LOW << (u32ChannelNum * 2 + PWM_WGCTL0_ZPCTL0_Pos));
        (pwm)->WGCTL1 &= ~((PWM_WGCTL1_CMPDCTL0_Msk | PWM_WGCTL1_CMPUCTL0_Msk) << (u32ChannelNum * 2));
        (pwm)->WGCTL1 |= (PWM_OUTPUT_HIGH << (u32ChannelNum * 2 + PWM_WGCTL1_CMPDCTL0_Pos));
    }
}

void BPWM_SetOutputChannel(BPWM_T *bpwm,uint32_t u32ChannelNum, uint16_t Timerperiod,uint16_t PWMduty, uint8_t u8Switch,uint32_t Prescaler)
{
    BPWM_SET_PRESCALER(bpwm, u32ChannelNum, Prescaler); // Divided by 1
    // set BPWM to down count type(edge aligned)
    (bpwm)->CTL1 = (1UL);

    BPWM_SET_CNR(bpwm, u32ChannelNum, Timerperiod);
    if(u8Switch)
    {
        BPWM_SET_CMR(bpwm, u32ChannelNum, PWMduty);
        (bpwm)->WGCTL0 &= ~((BPWM_WGCTL0_PRDPCTL0_Msk | BPWM_WGCTL0_ZPCTL0_Msk) << (u32ChannelNum * 2));
        (bpwm)->WGCTL0 |= (BPWM_OUTPUT_LOW << (u32ChannelNum * 2 + BPWM_WGCTL0_PRDPCTL0_Pos));
        (bpwm)->WGCTL1 &= ~((BPWM_WGCTL1_CMPDCTL0_Msk | BPWM_WGCTL1_CMPUCTL0_Msk) << (u32ChannelNum * 2));
        (bpwm)->WGCTL1 |= (BPWM_OUTPUT_HIGH << (u32ChannelNum * 2 + BPWM_WGCTL1_CMPDCTL0_Pos));
    }
    else
    {
        BPWM_SET_CMR(bpwm, u32ChannelNum, PWMduty);
        (bpwm)->WGCTL0 &= ~((BPWM_WGCTL0_PRDPCTL0_Msk | BPWM_WGCTL0_ZPCTL0_Msk) << (u32ChannelNum * 2));
        (bpwm)->WGCTL0 |= (BPWM_OUTPUT_LOW << (u32ChannelNum * 2 + BPWM_WGCTL0_ZPCTL0_Pos));
        (bpwm)->WGCTL1 &= ~((BPWM_WGCTL1_CMPDCTL0_Msk | BPWM_WGCTL1_CMPUCTL0_Msk) << (u32ChannelNum * 2));
        (bpwm)->WGCTL1 |= (BPWM_OUTPUT_HIGH << (u32ChannelNum * 2 + BPWM_WGCTL1_CMPDCTL0_Pos));
    }
}

void LedPwmInit(void){
   uint32_t i=0;
	//IO口功能选择
	/*
	*  PWM0_CH0---PA12 PWM1_CH0---PA2	BPWM0_CH0---PC0	  BPWM1_CH0---PD7
	*  PWM0_CH1---PA13 PWM1_CH1---PA3	BPWM0_CH1---PC1	  BPWM1_CH1---PD6
	*  PWM0_CH2---PA14 PWM1_CH2---PA10	BPWM0_CH2---PC2	  BPWM1_CH2---PB8
	*  PWM0_CH3---PA15 PWM1_CH3---PA11	BPWM0_CH3---PC3	  BPWM1_CH3---PB12
	*  PWM0_CH4---PA0  PWM1_CH4---PF4	BPWM0_CH4---PD15  BPWM1_CH4---PF8
	*  PWM0_CH5---PA1  PWM1_CH5---PF5	BPWM0_CH5---PD14  BPWM1_CH5---PB15
	*/
	
	SYS->GPA_MFP |= (SYS_GPA_MFP_PA12_PWM0_CH0| SYS_GPA_MFP_PA13_PWM0_CH1| SYS_GPA_MFP_PA14_PWM0_CH2| SYS_GPA_MFP_PA15_PWM0_CH3| 
		SYS_GPA_MFP_PA0_PWM0_CH4| SYS_GPA_MFP_PA1_PWM0_CH5|
		SYS_GPA_MFP_PA2_PWM1_CH0| SYS_GPA_MFP_PA3_PWM1_CH1| SYS_GPA_MFP_PA10_PWM1_CH2| SYS_GPA_MFP_PA11_PWM1_CH3);
	SYS->GPF_MFP |= ( SYS_GPF_MFP_PF4_PWM1_CH4| SYS_GPF_MFP_PF5_PWM1_CH5| SYS_GPF_MFP_PF8_BPWM1_CH4);

	SYS->GPD_MFP |= ( SYS_GPD_MFP_PD15_BPWM0_CH4| SYS_GPD_MFP_PD14_BPWM0_CH5| SYS_GPD_MFP_PD7_BPWM1_CH0| SYS_GPD_MFP_PD6_BPWM1_CH1 );
	SYS->GPB_MFP |= ( SYS_GPB_MFP_PB8_BPWM1_CH2| SYS_GPB_MFP_PB12_BPWM1_CH3| SYS_GPB_MFP_PB15_BPWM1_CH5 );
	SYS->GPC_MFP |= ( SYS_GPC_MFP_PC0_BPWM0_CH0| SYS_GPC_MFP_PC1_BPWM0_CH1| SYS_GPC_MFP_PC2_BPWM0_CH2| SYS_GPC_MFP_PC3_BPWM0_CH3 );	
			  	 
	SYS->ALT_MFP|= ( SYS_ALT_MFP_PA12_PWM0_CH0| SYS_ALT_MFP_PA13_PWM0_CH1| SYS_ALT_MFP_PA14_PWM0_CH2|	 //PWM0
		SYS_ALT_MFP_PA15_PWM0_CH3 |SYS_ALT_MFP_PA0_PWM0_CH4  |SYS_ALT_MFP_PA1_PWM0_CH5  |   
		SYS_ALT_MFP_PA2_PWM1_CH0  |SYS_ALT_MFP_PA3_PWM1_CH1  |SYS_ALT_MFP_PA10_PWM1_CH2 |				 //PWM1
		SYS_ALT_MFP_PA11_PWM1_CH3 |SYS_ALT_MFP_PF4_PWM1_CH4  |SYS_ALT_MFP_PF5_PWM1_CH5  |
		SYS_ALT_MFP_PC0_BPWM0_CH0 |SYS_ALT_MFP_PC1_BPWM0_CH1 |SYS_ALT_MFP_PC2_BPWM0_CH2 | 				 //BPWM0
		SYS_ALT_MFP_PC3_BPWM0_CH3 |SYS_ALT_MFP_PD15_BPWM0_CH4|SYS_ALT_MFP_PD14_BPWM0_CH5|
		SYS_ALT_MFP_PD7_BPWM1_CH0 |SYS_ALT_MFP_PD6_BPWM1_CH1 |SYS_ALT_MFP_PB8_BPWM1_CH2 |				 //BPWM1
		SYS_ALT_MFP_PB12_BPWM1_CH3|SYS_ALT_MFP_PF8_BPWM1_CH4 |SYS_ALT_MFP_PB15_BPWM1_CH5 );	  
	
	SYS->ALT_MFP2|= ( SYS_ALT_MFP2_PA12_PWM0_CH0| SYS_ALT_MFP2_PA13_PWM0_CH1| SYS_ALT_MFP2_PA14_PWM0_CH2|	 //PWM0
		SYS_ALT_MFP2_PA15_PWM0_CH3 |SYS_ALT_MFP2_PA0_PWM0_CH4  |SYS_ALT_MFP2_PA1_PWM0_CH5  |   
		SYS_ALT_MFP2_PA2_PWM1_CH0  |SYS_ALT_MFP2_PA3_PWM1_CH1  |SYS_ALT_MFP2_PA10_PWM1_CH2 |				 //PWM1
		SYS_ALT_MFP2_PA11_PWM1_CH3 |SYS_ALT_MFP2_PF4_PWM1_CH4  |SYS_ALT_MFP2_PF5_PWM1_CH5  |
		SYS_ALT_MFP2_PC0_BPWM0_CH0 |SYS_ALT_MFP2_PC1_BPWM0_CH1 |SYS_ALT_MFP2_PC2_BPWM0_CH2 | 				 //BPWM0
		SYS_ALT_MFP2_PC3_BPWM0_CH3 |SYS_ALT_MFP2_PD15_BPWM0_CH4|SYS_ALT_MFP2_PD14_BPWM0_CH5|
		SYS_ALT_MFP2_PD7_BPWM1_CH0 |SYS_ALT_MFP2_PD6_BPWM1_CH1 |SYS_ALT_MFP2_PB8_BPWM1_CH2 |				 //BPWM1
		SYS_ALT_MFP2_PB12_BPWM1_CH3|SYS_ALT_MFP2_PF8_BPWM1_CH4 |SYS_ALT_MFP2_PB15_BPWM1_CH5 );	  
	
	SYS->ALT_MFP3|= ( SYS_ALT_MFP3_PA12_PWM0_CH0| SYS_ALT_MFP3_PA13_PWM0_CH1| SYS_ALT_MFP3_PA14_PWM0_CH2|	 //PWM0
		SYS_ALT_MFP3_PA15_PWM0_CH3 |SYS_ALT_MFP3_PA0_PWM0_CH4  |SYS_ALT_MFP3_PA1_PWM0_CH5  |   
		SYS_ALT_MFP3_PA2_PWM1_CH0  |SYS_ALT_MFP3_PA3_PWM1_CH1  |SYS_ALT_MFP3_PA10_PWM1_CH2 |				 //PWM1
		SYS_ALT_MFP3_PA11_PWM1_CH3 |SYS_ALT_MFP3_PF4_PWM1_CH4  |SYS_ALT_MFP3_PF5_PWM1_CH5  |
		SYS_ALT_MFP3_PC0_BPWM0_CH0 |SYS_ALT_MFP3_PC1_BPWM0_CH1 |SYS_ALT_MFP3_PC2_BPWM0_CH2 | 				 //BPWM0
		SYS_ALT_MFP3_PC3_BPWM0_CH3 |SYS_ALT_MFP3_PD15_BPWM0_CH4|SYS_ALT_MFP3_PD14_BPWM0_CH5|
		SYS_ALT_MFP3_PD7_BPWM1_CH0 |SYS_ALT_MFP3_PD6_BPWM1_CH1 |SYS_ALT_MFP3_PB8_BPWM1_CH2 |				 //BPWM1
		SYS_ALT_MFP3_PB12_BPWM1_CH3|SYS_ALT_MFP3_PF8_BPWM1_CH4 |SYS_ALT_MFP3_PB15_BPWM1_CH5 );	  
	
	SYS->ALT_MFP4|= ( SYS_ALT_MFP4_PA12_PWM0_CH0| SYS_ALT_MFP4_PA13_PWM0_CH1| SYS_ALT_MFP4_PA14_PWM0_CH2|	 //PWM0
		SYS_ALT_MFP4_PA15_PWM0_CH3 |SYS_ALT_MFP4_PA0_PWM0_CH4  |SYS_ALT_MFP4_PA1_PWM0_CH5  |   
		SYS_ALT_MFP4_PA2_PWM1_CH0  |SYS_ALT_MFP4_PA3_PWM1_CH1  |SYS_ALT_MFP4_PA10_PWM1_CH2 |				 //PWM1
		SYS_ALT_MFP4_PA11_PWM1_CH3 |SYS_ALT_MFP4_PF4_PWM1_CH4  |SYS_ALT_MFP4_PF5_PWM1_CH5  |
		SYS_ALT_MFP4_PC0_BPWM0_CH0 |SYS_ALT_MFP4_PC1_BPWM0_CH1 |SYS_ALT_MFP4_PC2_BPWM0_CH2 | 				 //BPWM0
		SYS_ALT_MFP4_PC3_BPWM0_CH3 |SYS_ALT_MFP4_PD15_BPWM0_CH4|SYS_ALT_MFP4_PD14_BPWM0_CH5|
		SYS_ALT_MFP4_PD7_BPWM1_CH0 |SYS_ALT_MFP4_PD6_BPWM1_CH1 |SYS_ALT_MFP4_PB8_BPWM1_CH2 |				 //BPWM1
		SYS_ALT_MFP4_PB12_BPWM1_CH3|SYS_ALT_MFP4_PF8_BPWM1_CH4 |SYS_ALT_MFP4_PB15_BPWM1_CH5 );	  	
	 // PWM0 Group ( 0, 1, 2, 3, 4 5 )
	 CLK_EnableModuleClock(PWM0_MODULE);
 //    CLK_SetModuleClock(PWM0_MODULE, CLK_CLKSEL3_PWM0_S_PLL, 0);	 //Select PWM module clock source

	 CLK->CLKSEL3 &= ~CLK_CLKSEL3_PWM0_S_PCLK;
     SYS_ResetModule(PWM0_RST);     //Reset PWM0 

	 PWM_SetOutputChannel(PWM0,0,XPWM_CNR_VAL_SET,XPWM_INIT_SET,SWITCH_SET,0);
	 PWM_SetOutputChannel(PWM0,1,XPWM_CNR_VAL_SET,XPWM_INIT_SET,SWITCH_SET,0);
	 PWM_SetOutputChannel(PWM0,2,XPWM_CNR_VAL_SET,XPWM_INIT_SET,SWITCH_SET,0);
	 PWM_SetOutputChannel(PWM0,3,XPWM_CNR_VAL_SET,XPWM_INIT_SET,SWITCH_SET,0);
	 PWM_SetOutputChannel(PWM0,4,XPWM_CNR_VAL_SET,XPWM_INIT_SET,SWITCH_SET,0);
	 PWM_SetOutputChannel(PWM0,5,XPWM_CNR_VAL_SET,XPWM_INIT_SET,SWITCH_SET,0);

	 PWM_EnableOutput( PWM0, BPWM_CH_0_MASK| BPWM_CH_1_MASK | BPWM_CH_2_MASK | BPWM_CH_3_MASK |BPWM_CH_4_MASK | BPWM_CH_5_MASK);

	 //PWM1 Group ( 0, 1, 2, 3, 4, 5)
	 CLK_EnableModuleClock(PWM1_MODULE);
 //    CLK_SetModuleClock(PWM1_MODULE, CLK_CLKSEL3_PWM1_S_PLL , 0);	 //Select PWM module clock source
     CLK->CLKSEL3 &= ~CLK_CLKSEL3_PWM1_S_PCLK;
     SYS_ResetModule(PWM1_RST);     //Reset PWM1 

	 PWM_SetOutputChannel(PWM1,0,XPWM_CNR_VAL_SET,XPWM_INIT_SET,SWITCH_SET,0);
	 PWM_SetOutputChannel(PWM1,1,XPWM_CNR_VAL_SET,XPWM_INIT_SET,SWITCH_SET,0);
	 PWM_SetOutputChannel(PWM1,2,XPWM_CNR_VAL_SET,XPWM_INIT_SET,SWITCH_SET,0);
	 PWM_SetOutputChannel(PWM1,3,XPWM_CNR_VAL_SET,XPWM_INIT_SET,SWITCH_SET,0);
	 PWM_SetOutputChannel(PWM1,4,XPWM_CNR_VAL_SET,XPWM_INIT_SET,SWITCH_SET,0);
	 PWM_SetOutputChannel(PWM1,5,XPWM_CNR_VAL_SET,XPWM_INIT_SET,SWITCH_SET,0);

	 PWM_EnableOutput( PWM1, BPWM_CH_0_MASK| BPWM_CH_1_MASK | BPWM_CH_2_MASK | BPWM_CH_3_MASK |BPWM_CH_4_MASK | BPWM_CH_5_MASK);
	 
	 //BPWM0 Group( 0, 1, 2, 3, 4, 5 )
     CLK_EnableModuleClock(BPWM0_MODULE);
//   CLK_SetModuleClock(BPWM0_MODULE, CLK_CLKSEL3_BPWM0_S_PLL, 0);	 //Select PWM module clock source
     CLK->CLKSEL3 &= ~CLK_CLKSEL3_BPWM0_S_PCLK;
     SYS_ResetModule(BPWM0_RST); 									  //Reset BPWM0                                    

     BPWM_SetOutputChannel(BPWM0,0,XPWM_CNR_VAL_SET,XPWM_INIT_SET,SWITCH_SET,0);
	 BPWM_SetOutputChannel(BPWM0,1,XPWM_CNR_VAL_SET,XPWM_INIT_SET,SWITCH_SET,0);
	 BPWM_SetOutputChannel(BPWM0,2,XPWM_CNR_VAL_SET,XPWM_INIT_SET,SWITCH_SET,0);
	 BPWM_SetOutputChannel(BPWM0,3,XPWM_CNR_VAL_SET,XPWM_INIT_SET,SWITCH_SET,0);
	 BPWM_SetOutputChannel(BPWM0,4,XPWM_CNR_VAL_SET,XPWM_INIT_SET,SWITCH_SET,0);
	 BPWM_SetOutputChannel(BPWM0,5,XPWM_CNR_VAL_SET,XPWM_INIT_SET,SWITCH_SET,0);

	 BPWM_EnableOutput( BPWM0, BPWM_CH_0_MASK|BPWM_CH_1_MASK | BPWM_CH_2_MASK | BPWM_CH_3_MASK |BPWM_CH_4_MASK | BPWM_CH_5_MASK );
	 
	 //BPWM1 Group ( 0,1,2,3, 4, 5)
	 CLK_EnableModuleClock(BPWM1_MODULE);
//   CLK_SetModuleClock(BPWM1_MODULE, CLK_CLKSEL3_BPWM1_S_PLL, 0);	 //Select PWM module clock source
     CLK->CLKSEL3 &= ~CLK_CLKSEL3_BPWM1_S_PCLK;
     SYS_ResetModule(BPWM1_RST); 									  //Reset BPWM1                                    

     BPWM_SetOutputChannel(BPWM1,0,XPWM_CNR_VAL_SET,XPWM_INIT_SET,SWITCH_SET,0);
	 BPWM_SetOutputChannel(BPWM1,1,XPWM_CNR_VAL_SET,XPWM_INIT_SET,SWITCH_SET,0);
	 BPWM_SetOutputChannel(BPWM1,2,XPWM_CNR_VAL_SET,XPWM_INIT_SET,SWITCH_SET,0);
	 BPWM_SetOutputChannel(BPWM1,3,XPWM_CNR_VAL_SET,XPWM_INIT_SET,SWITCH_SET,0);
	 BPWM_SetOutputChannel(BPWM1,4,XPWM_CNR_VAL_SET,XPWM_INIT_SET,SWITCH_SET,0);
	 BPWM_SetOutputChannel(BPWM1,5,XPWM_CNR_VAL_SET,XPWM_INIT_SET,SWITCH_SET,0);

	 BPWM_EnableOutput( BPWM1, BPWM_CH_0_MASK| BPWM_CH_1_MASK | BPWM_CH_2_MASK | BPWM_CH_3_MASK |BPWM_CH_4_MASK | BPWM_CH_5_MASK );
     
	 PWM_Start( PWM0, PWM_CH_0_MASK| PWM_CH_1_MASK | PWM_CH_2_MASK | PWM_CH_3_MASK |PWM_CH_4_MASK | PWM_CH_5_MASK); 
     PWM_Start( PWM1, PWM_CH_0_MASK| PWM_CH_1_MASK | PWM_CH_2_MASK | PWM_CH_3_MASK |PWM_CH_4_MASK | PWM_CH_5_MASK); 

     BPWM_Start( BPWM0, BPWM_CH_0_MASK| BPWM_CH_1_MASK | BPWM_CH_2_MASK | BPWM_CH_3_MASK |BPWM_CH_4_MASK | BPWM_CH_5_MASK);	 
	 BPWM_Start( BPWM1, BPWM_CH_0_MASK| BPWM_CH_1_MASK | BPWM_CH_2_MASK | BPWM_CH_3_MASK |BPWM_CH_4_MASK | BPWM_CH_5_MASK);

	 for(i=0;i<LED_TOTAL;i++){
	 	Led.LED_PWM[i]=0;
		Led.LED_PWM_[i]=0;
	 }
}


void LedPwmOutput(uint16_t*p)
{
	//PWM0
	PWM_SET_CMR(PWM0, 0, *(p+LED1));
	PWM_SET_CMR(PWM0, 1, *(p+LED2));
	PWM_SET_CMR(PWM0, 2, *(p+LED3));
	PWM_SET_CMR(PWM0, 3, *(p+LED4));
	PWM_SET_CMR(PWM0, 4, *(p+LED5));
	PWM_SET_CMR(PWM0, 5, *(p+LED6));	
	//PWM1
	PWM_SET_CMR(PWM1, 0, *(p+LED7));
	PWM_SET_CMR(PWM1, 1, *(p+LED8)); //
	PWM_SET_CMR(PWM1, 2, *(p+LED9));
	PWM_SET_CMR(PWM1, 3, *(p+LED10));
	PWM_SET_CMR(PWM1, 4, *(p+LED11));
	PWM_SET_CMR(PWM1, 5, *(p+LED12));	
	//BPWM0
	BPWM_SET_CMR(BPWM0, 0, *(p+LED13));
	BPWM_SET_CMR(BPWM0, 1, *(p+LED14));
	BPWM_SET_CMR(BPWM0, 2, *(p+LED15));
	BPWM_SET_CMR(BPWM0, 3, *(p+LED16));
	BPWM_SET_CMR(BPWM0, 4, *(p+LED17));
	BPWM_SET_CMR(BPWM0, 5, *(p+LED18));	  	
	//BPWM1
	BPWM_SET_CMR(BPWM1, 0, *(p+LED19));
	BPWM_SET_CMR(BPWM1, 1, *(p+LED20));
	BPWM_SET_CMR(BPWM1, 2, *(p+LED21));
	BPWM_SET_CMR(BPWM1, 3, *(p+LED22));
	BPWM_SET_CMR(BPWM1, 4, *(p+LED23));
	BPWM_SET_CMR(BPWM1, 5, *(p+LED24));
}










